import { ROLES, RoleSlug } from './constants';

export const PERMISSIONS = {
  // Users
  USERS_VIEW: 'users:view',
  USERS_CREATE: 'users:create',
  USERS_UPDATE: 'users:update',
  // Sales
  SALES_VIEW: 'sales:view',
  SALES_CREATE: 'sales:create',
  SALES_APPROVE: 'sales:approve',
  // Inventory
  INVENTORY_VIEW: 'inventory:view',
  INVENTORY_CREATE: 'inventory:create',
  INVENTORY_APPROVE: 'inventory:approve',
  // Expenses
  EXPENSES_VIEW: 'expenses:view',
  EXPENSES_CREATE: 'expenses:create',
  // Vendors
  VENDORS_VIEW: 'vendors:view',
  VENDORS_MANAGE: 'vendors:manage',
  // Attendance
  ATTENDANCE_VIEW: 'attendance:view',
  ATTENDANCE_CHECKIN: 'attendance:checkin',
  // Reports
  REPORTS_VIEW: 'reports:view',
  // Assets
  ASSETS_VIEW: 'assets:view',
  ASSETS_MANAGE: 'assets:manage',
  // Dashboard
  DASHBOARD_GROUP: 'dashboard:group',
  DASHBOARD_SUBSIDIARY: 'dashboard:subsidiary',
  // Accounting (Station)
  ACCOUNTS_VIEW: 'accounts:view',
  ACCOUNTS_MANAGE: 'accounts:manage',
  JOURNAL_VIEW: 'journal:view',
  JOURNAL_CREATE: 'journal:create',
  AR_VIEW: 'ar:view',
  AR_MANAGE: 'ar:manage',
  FINANCIAL_REPORTS: 'financial:reports',
  // Hospitality (Air BNB)
  BOOKINGS_VIEW: 'bookings:view',
  BOOKINGS_MANAGE: 'bookings:manage',
  GUESTS_VIEW: 'guests:view',
  GUESTS_MANAGE: 'guests:manage',
  ROOMS_VIEW: 'rooms:view',
  ROOMS_MANAGE: 'rooms:manage',
  HOUSEKEEPING_VIEW: 'housekeeping:view',
  HOUSEKEEPING_MANAGE: 'housekeeping:manage',
  // Settings
  SETTINGS_VIEW: 'settings:view',
  SETTINGS_MANAGE: 'settings:manage',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const ACCOUNTING_PERMS: Permission[] = [
  PERMISSIONS.ACCOUNTS_VIEW,
  PERMISSIONS.ACCOUNTS_MANAGE,
  PERMISSIONS.JOURNAL_VIEW,
  PERMISSIONS.JOURNAL_CREATE,
  PERMISSIONS.AR_VIEW,
  PERMISSIONS.AR_MANAGE,
  PERMISSIONS.FINANCIAL_REPORTS,
  PERMISSIONS.VENDORS_VIEW,
  PERMISSIONS.EXPENSES_VIEW,
  PERMISSIONS.REPORTS_VIEW,
];

const HOSPITALITY_PERMS: Permission[] = [
  PERMISSIONS.BOOKINGS_VIEW,
  PERMISSIONS.BOOKINGS_MANAGE,
  PERMISSIONS.GUESTS_VIEW,
  PERMISSIONS.GUESTS_MANAGE,
  PERMISSIONS.ROOMS_VIEW,
  PERMISSIONS.ROOMS_MANAGE,
  PERMISSIONS.HOUSEKEEPING_VIEW,
  PERMISSIONS.HOUSEKEEPING_MANAGE,
  PERMISSIONS.REPORTS_VIEW,
];

export const ROLE_PERMISSIONS: Record<RoleSlug, Permission[]> = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ROLES.ADMIN]: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_APPROVE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_APPROVE,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.VENDORS_VIEW,
    PERMISSIONS.VENDORS_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CHECKIN,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.ASSETS_VIEW,
    PERMISSIONS.ASSETS_MANAGE,
    PERMISSIONS.DASHBOARD_GROUP,
    PERMISSIONS.DASHBOARD_SUBSIDIARY,
    PERMISSIONS.SETTINGS_VIEW,
    ...ACCOUNTING_PERMS,
    ...HOSPITALITY_PERMS,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_APPROVE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_APPROVE,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.VENDORS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.ASSETS_VIEW,
    PERMISSIONS.DASHBOARD_SUBSIDIARY,
    PERMISSIONS.BOOKINGS_VIEW,
    PERMISSIONS.GUESTS_VIEW,
    PERMISSIONS.ROOMS_VIEW,
    PERMISSIONS.HOUSEKEEPING_VIEW,
  ],
  [ROLES.SALES_AGENT]: [
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.DASHBOARD_SUBSIDIARY,
  ],
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.VENDORS_VIEW,
    PERMISSIONS.DASHBOARD_SUBSIDIARY,
    ...ACCOUNTING_PERMS,
  ],
  [ROLES.INVENTORY_OFFICER]: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_CREATE,
    PERMISSIONS.INVENTORY_APPROVE,
    PERMISSIONS.VENDORS_VIEW,
    PERMISSIONS.VENDORS_MANAGE,
    PERMISSIONS.DASHBOARD_SUBSIDIARY,
  ],
  [ROLES.SECURITY]: [
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_CHECKIN,
    PERMISSIONS.DASHBOARD_SUBSIDIARY,
  ],
  [ROLES.HR]: [
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.DASHBOARD_SUBSIDIARY,
  ],
  [ROLES.GUEST_MANAGER]: [
    PERMISSIONS.DASHBOARD_SUBSIDIARY,
    ...HOSPITALITY_PERMS,
  ],
  [ROLES.RECEPTIONIST]: [
    PERMISSIONS.DASHBOARD_SUBSIDIARY,
    ...HOSPITALITY_PERMS,
  ],
};

export function hasPermission(userPermissions: string[], required: Permission): boolean {
  return userPermissions.includes(required);
}

export function hasAnyPermission(userPermissions: string[], required: Permission[]): boolean {
  return required.some((p) => userPermissions.includes(p));
}
